
services:
  db:
    image: mysql:latest
    container_name: "data-base"
    volumes:
      - dbase:/var/lib/mysql
    ports:
      - "3306:3306"
    expose:
      - 3306
    environment:
      MYSQL_ROOT_PASSWORD: dbDesafio
      MYSQL_DATABASE: desafio_db

  phpmyadmin:
    image: phpmyadmin
    ports:
      - 8000:80

  app:
    depends_on:
      - db
    build:
      context: ./
      dockerfile: Dockerfile
    restart: on-failure
    ports:
      - "4500:4500"

volumes:
  dbase:
