server:
  port: 8080

spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3306/desafio?useTimezone=true&serverTimezone=UTC
    username: root
    drive-class-name: com.mysql.cj.jdbc.Driver
    platform: mysql

spring-doc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html